### ISSUE TITLE
Add community to "Welcome" text

### ISSUE THREAD

**Issue by nthnjustice** [PowerShareInternational/MedfordBeta#5]
Add community's name in the same color/font as the logo (replace the word "Welcome")

**Comment by nthnjustice** [comment]
@PowerShare What do you mean with the following:

"Then I think we want the subtitle under "Medford." I want to create an impression that Medford "owns" this page, almost like "PowerShare Medford" has its own separate logo from "PowerShare.""

Do you want another subititle under "Medford"? What should it say?

**Comment by PowerShare** [comment]
Good evening, Nathan. Let's put the same subtitle from the home page under the name of the city. So under "Medford" it would read, "Prioritize Your Community's Goals" . . . Sorry for the lack of clarity.
